# Generated by Django 6.0.1 on 2026-04-29 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_publicidade_servico_ativo_servico_preco_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de', models.CharField(max_length=200)),
                ('email_remetente', models.EmailField(max_length=254)),
                ('assunto', models.CharField(max_length=300)),
                ('mensagem', models.TextField()),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('nao_lido', 'Não Lido'), ('lido', 'Lido'), ('respondido', 'Respondido'), ('arquivado', 'Arquivado')], default='nao_lido', max_length=20)),
                ('recebido_em', models.DateTimeField(auto_now_add=True)),
                ('respondido_em', models.DateTimeField(blank=True, null=True)),
                ('agendamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='core.agendamento')),
            ],
            options={
                'ordering': ['-recebido_em'],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('agendamento', 'Novo Agendamento'), ('cliente', 'Novo Cliente'), ('servico', 'Novo Serviço'), ('publicidade', 'Nova Publicidade'), ('confirmacao', 'Confirmação de Agendamento'), ('cancelamento', 'Cancelamento de Agendamento'), ('sistema', 'Mensagem do Sistema')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('icone', models.CharField(default='fas fa-bell', max_length=50)),
                ('cor', models.CharField(default='#007bff', max_length=50)),
                ('lida', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
                ('agendamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.agendamento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notificações',
                'ordering': ['-criada_em'],
            },
        ),
    ]
