# Generated by Django 6.0.1 on 2026-05-25 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_email_notificacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_remetente', models.CharField(choices=[('admin', 'Administrador'), ('cliente', 'Cliente')], max_length=10)),
                ('assunto', models.CharField(blank=True, max_length=200)),
                ('conteudo', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('respondida', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('lida_em', models.DateTimeField(blank=True, null=True)),
                ('agendamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='core.agendamento')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_recebidas', to=settings.AUTH_USER_MODEL)),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Mensagens',
                'ordering': ['-criada_em'],
            },
        ),
    ]
