# Generated by Django 6.0.1 on 2026-06-03 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='atendido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('expirado', 'Expirado'), ('atendido', 'Atendido'), ('nao_compareceu', 'Não Compareceu'), ('cancelado', 'Cancelado')], default='pendente', max_length=20),
        ),
    ]
