# Generated by Django 6.0.1 on 2026-06-09 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_agendamento_atendido_em_alter_agendamento_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'ordering': ['-criado_em'], 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AddField(
            model_name='agendamento',
            name='confirmado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='metodo_pagamento',
            field=models.CharField(blank=True, choices=[('cartao', 'Cartão Bancário'), ('multicaixa', 'Multicaixa Express'), ('transferencia', 'Transferência Bancária'), ('presencial', 'Pagamento Presencial')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='referencia_pagamento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='status_pagamento',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('falhou', 'Falhou'), ('reembolsado', 'Reembolsado')], default='pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='valor_pagamento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('agendamento', 'Novo Agendamento'), ('cliente', 'Novo Cliente'), ('servico', 'Novo Serviço'), ('publicidade', 'Nova Publicidade'), ('confirmacao', 'Confirmação de Agendamento'), ('cancelamento', 'Cancelamento de Agendamento'), ('pagamento', 'Pagamento Recebido'), ('sistema', 'Mensagem do Sistema')], max_length=20),
        ),
    ]
