# Generated by Django 6.0.1 on 2026-06-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_agendamento_options_agendamento_confirmado_em_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='atendido_em',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='status',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='cancelado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='pago_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='status_confirmacao',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('nao_apareceu', 'Não Apareceu')], default='pendente', max_length=20, verbose_name='Status de Confirmação'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='metodo_pagamento',
            field=models.CharField(choices=[('presencial', 'Pagamento Presencial')], default='presencial', max_length=20, verbose_name='Método de Pagamento'),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='status_pagamento',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago')], default='pendente', max_length=20, verbose_name='Status de Pagamento'),
        ),
    ]
